import './globals.css';
import { AuthProvider } from './Auth';
import { Inter } from 'next/font/google';
import { getAuthConfig } from '@supabase/auth-ui-shared';
import { Header } from './Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const config = await getAuthConfig(
		process.env.NEXT_PUBLIC_SUPABASE_URL as string,
		process.env.NEXT_PUBLIC_SUPABASE_KEY as string
	);

	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider config={config}>
					<Header></Header>
					<main>{children}</main>
				</AuthProvider>
			</body>
		</html>
	);
}
